### ISSUE TITLE
Cannot set Genpipes version

### ISSUE THREAD

**Issue by ramou** [c3g/genpipes_in_a_container#1]
If I understand init_all.sh correctly, it would appear that the foreach does not filter all the opts that could be used in the following switch. Specifically line 27:
```while getopts ":a:d:c:p:" opt; do```
should probably be
```while getopts ":a:c:p:V:d" opt; do```

I've re-ordered based on the order in the switch, but I suspect making the order consistent there, in the usage and in the switch is a good idea too.

**Comment by poquirion** [comment]
It is in the 0.4 version... I will make sure to republish the container with the right options

**Comment by poquirion** [comment]
fixed in release 0.7
