### ISSUE TITLE
The default CVMFS_CACHE_BASE specified in default.local can cause problems when not running as root

### ISSUE THREAD

**Issue by ramou** [c3g/genpipes_in_a_container#3]
When running as root, it is fine. However, when not run as root there is no access and it in general seems likely to cause difficulties.

Specifically, this is the default -a argument used to initialize the image, if not otherwise pass as an argument. I've had some luck using:
```-a /tmp/$USER/cvmfs-cache```

but I'm execing _init_genpipes_ from the container call and I cannot guarantee ```$USER``` is as expected from within docker/singularity.

**Comment by poquirion** [comment]
I think $USER with singularity will always be what is expected but with docker, I am not sure...
I will run a couple test, but I think it is a good idea.

**Comment by poquirion** [comment]
$UID is, unlike $USER always defined, i'll use that.

**Comment by poquirion** [comment]
oups, of course the parrot already does that by default, using /tmp/parrot.UID. I will just keep that as the default.
